#ifndef DECEN_OBJ_H_
#define DECEN_OBJ_H_

#include "CxOOP.h"
#include "CHILD_OBJ.h"

#define DECEN_OBJ_DNA_(X,COBJ)              CxOOP_EXTENDS2_(CHILD_OBJ,X,COBJ)

#define DECEN_OBJ_PUBLIC_MEMBER_            int decendent_data;
#define DECEN_OBJ_PRIVATE_MEMBER_

#define DECEN_OBJ_PUBLIC_METHOD_(COBJ,MACRO_X)
#define DECEN_OBJ_PRIVATE_METHOD_(COBJ,MACRO_X)
#define DECEN_OBJ_OVERRIDE_METHOD_(COBJ,MACRO_X) \
        MACRO_X(COBJ,int,DoAction, COBJ* self)

CxOOP_OBJECT_DECLARE(DECEN_OBJ)
int CONSTRUCTOR_DECEN_OBJ(DECEN_OBJ* obj);

#endif

